language: python
python:
  - "3.6"
  - "3.7"
env:
  - NUMPY="numpy==1.15.0"
  - NUMPY="numpy==1.16.6"
  - NUMPY="numpy"
install:
  - pip install cython>=0.28
  - pip install "$NUMPY" scipy matplotlib
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
       pip install raysect;
    else
       pip install git+https://github.com/raysect/source@development;
    fi
  - dev/build.sh
# command to run tests
script: dev/test.sh
